# These are supported funding model platforms

github: ["sarumaj"] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
tidelift: "pypi/unbabelizer" # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ["paypal.me/danviddo"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
buy_me_a_coffee: "sarumaj"
